In [1]:
!pip install git+https://github.com/PrithivirajDamodaran/Styleformer.git

Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/PrithivirajDamodaran/Styleformer.git
  Cloning https://github.com/PrithivirajDamodaran/Styleformer.git to /scratch/local/61160211/pip-req-build-co0s0r2g
  Running command git clone -q https://github.com/PrithivirajDamodaran/Styleformer.git /scratch/local/61160211/pip-req-build-co0s0r2g
Requirement already satisfied: transformers in /home/chirayu.tripathi/.local/lib/python3.8/site-packages (from styleformer==0.1) (4.26.1)
Collecting sentencepiece
  Downloading sentencepiece-0.1.97-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     |████████████████████████████████| 1.3 MB 8.6 MB/s eta 0:00:01
Collecting python-Levenshtein
  Downloading python_Levenshtein-0.20.9-py3-none-any.whl (9.4 kB)
Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: regex!=2019.12.17 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from transformers->styleformer==0.1) (2020.11.13)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in /home/chirayu.tripathi/.local/lib/python3.8/site-packages (from transformers->styleformer==0.1) (0.13.2)
Requirement already satisfied: tqdm>=4.27 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from transformers->styleformer==0.1) (4.64.1)
Requirement already satisfied: requests in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from transformers->styleformer==0.1) (2.22.0)
Requirement already satisfied: packaging>=20.0 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from transformers->styleformer==0.1) (20.4)
Requirement already satisfied: filelock in /home/chirayu.tripathi/.local/lib/python3.8/site-packages (from transformers->styleformer==0.1) (3.9.0)
Requirement already satisfied: numpy>=1.17 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from transformers->styleformer==0.1) (1.20.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.11.0 in /home/chirayu.tripathi/.local/lib/python3.8/site-packages (from transformers->styleformer==0.1) (0.12.0)
Requirement already satisfied: pyyaml>=5.1 in /home/chirayu.tripathi/.local/lib/python3.8/site-packages (from transformers->styleformer==0.1) (6.0)
Collecting Levenshtein==0.20.9
  Downloading Levenshtein-0.20.9-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (174 kB)
     |████████████████████████████████| 174 kB 115.0 MB/s eta 0:00:01
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->transformers->styleformer==0.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->transformers->styleformer==0.1) (2021.10.8)
Requirement already satisfied: idna<2.9,>=2.5 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->transformers->styleformer==0.1) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->transformers->styleformer==0.1) (1.25.7)
Requirement already satisfied: six in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from packaging>=20.0->transformers->styleformer==0.1) (1.14.0)
Requirement already satisfied: pyparsing>=2.0.2 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from packaging>=20.0->transformers->styleformer==0.1) (2.4.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/chirayu.tripathi/.local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.11.0->transformers->styleformer==0.1) (4.5.0)
Collecting rapidfuzz<3.0.0,>=2.3.0
  Downloading rapidfuzz-2.15.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 106.3 MB/s eta 0:00:01█    | 1.9 MB 106.3 MB/s eta 0:00:01
Building wheels for collected packages: styleformer
  Building wheel for styleformer (setup.py) ... done
  Created wheel for styleformer: filename=styleformer-0.1-py3-none-any.whl size=8614 sha256=aef72c10776089bf11f62a38f9e0eaa86cf2c589f1ddccc043ee558f941bd14c
  Stored in directory: /scratch/local/61160211/pip-ephem-wheel-cache-3rw04w5n/wheels/8e/fe/51/c675427268a6329f612bb74a6822bd2d354ab022210397b88e
Successfully built styleformer
Installing collected packages: sentencepiece, rapidfuzz, Levenshtein, python-Levenshtein, fuzzywuzzy, styleformer
Successfully installed Levenshtein-0.20.9 fuzzywuzzy-0.18.0 python-Levenshtein-0.20.9 rapidfuzz-2.15.0 sentencepiece-0.1.97 styleformer-0.1

In [2]:
from styleformer import Styleformer
import torch
import warnings
warnings.filterwarnings("ignore")

In [28]:
sf = Styleformer(style = 3)

Downloading (…)lve/main/config.json:   0%|          | 0.00/913 [00:00<?, ?B/s]

Downloading (…)"pytorch_model.bin";:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Downloading (…)olve/main/vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

Downloading (…)olve/main/merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

Downloading (…)okenizer_config.json:   0%|          | 0.00/1.89k [00:00<?, ?B/s]

Downloading (…)lve/main/config.json:   0%|          | 0.00/1.39k [00:00<?, ?B/s]

Downloading (…)"spiece.model";:   0%|          | 0.00/792k [00:00<?, ?B/s]

Downloading (…)/main/tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

Downloading (…)cial_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

Downloading (…)"pytorch_model.bin";:   0%|          | 0.00/242M [00:00<?, ?B/s]

Passive to Active model loaded...

In [4]:
# 1
source_sentences = [
"How many heads of the departments are older than 56 ?",
"What are the names of the states where at least 3 heads were born",

]   

for source_sentence in source_sentences:
    target_sentence = sf.transfer(source_sentence)
    print("-" *100)
    print("[Casual] ", source_sentence)
    print("-" *100)
    if target_sentence is not None:
        print("[Formal] ",target_sentence)
        print()
    else:
        print("No good quality transfers available !")

----------------------------------------------------------------------------------------------------
[Casual]  How many heads of the departments are older than 56 ?
----------------------------------------------------------------------------------------------------
[Formal]  how many heads of department are over 56?

----------------------------------------------------------------------------------------------------
[Casual]  What are the names of the states where at least 3 heads were born
----------------------------------------------------------------------------------------------------
[Formal]  What are the states where at least 3 heads were born.

In [6]:
# 0 
source_sentences = [
"How many heads of the departments are older than 56 ?",
"What are the names of the states where at least 3 heads were born",

]   

for source_sentence in source_sentences:
    target_sentence = sf.transfer(source_sentence)
    print("-" *100)
    print("[Casual] ", source_sentence)
    print("-" *100)
    if target_sentence is not None:
        print("[Formal] ",target_sentence)
        print()
    else:
        print("No good quality transfers available !")

----------------------------------------------------------------------------------------------------
[Casual]  How many heads of the departments are older than 56 ?
----------------------------------------------------------------------------------------------------
[Formal]  How many heads of department are older than 56?

----------------------------------------------------------------------------------------------------
[Casual]  What are the names of the states where at least 3 heads were born
----------------------------------------------------------------------------------------------------
[Formal]  What are the names of the states in which at least three heads were born.

In [8]:
# 2
source_sentences = [
"How many heads of the departments are older than 56 ?",
"What are the names of the states where at least 3 heads were born",

]   

for source_sentence in source_sentences:
    target_sentence = sf.transfer(source_sentence)
    print("-" *100)
    print("[Casual] ", source_sentence)
    print("-" *100)
    if target_sentence is not None:
        print("[Formal] ",target_sentence)
        print()
    else:
        print("No good quality transfers available !")

----------------------------------------------------------------------------------------------------
[Casual]  How many heads of the departments are older than 56 ?
----------------------------------------------------------------------------------------------------
[Formal]  How many heads of the departments are older than 56?

----------------------------------------------------------------------------------------------------
[Casual]  What are the names of the states where at least 3 heads were born
----------------------------------------------------------------------------------------------------
[Formal]  Welche are the names of the states where at least 3 heads were born

In [30]:
# 3
source_sentences = [
"In which year were most departments established",
"How many departments are led by heads who are not mentioned?",

]   

for source_sentence in source_sentences:
    target_sentence = sf.transfer(source_sentence)
    print("-" *100)
    print("[Casual] ", source_sentence)
    print("-" *100)
    if target_sentence is not None:
        print("[Formal] ",target_sentence)
        print()
    else:
        print("No good quality transfers available !")

----------------------------------------------------------------------------------------------------
[Casual]  In which year were most departments established
----------------------------------------------------------------------------------------------------
[Formal]  In which year were most departments established

----------------------------------------------------------------------------------------------------
[Casual]  How many departments are led by heads who are not mentioned?
----------------------------------------------------------------------------------------------------
[Formal]  How many departments lead heads who are not mentioned?

In [12]:
from PassivePySrc import PassivePy
passivepy = PassivePy.PassivePyAnalyzer(spacy_model = "en_core_web_lg")

In [26]:
sample_text = "food was cooked by me"
passivepy.match_text(sample_text, full_passive=True, truncated_passive=True)['binary'][0]

1

In [1]:
import pandas as pd
df = pd.read_csv('/home/chirayu.tripathi/t5/data_input_questions.csv')

In [35]:
!pip install ai21

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
Defaulting to user installation because normal site-packages is not writeable
Collecting ai21
  Downloading ai21-1.0.3.tar.gz (8.2 kB)
Requirement already satisfied: requests in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from ai21) (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->ai21) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->ai21) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->ai21) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /apps/jupyterhub/1.1.0/lib/python3.8/site-packages (from requests->ai21) (2021.10.8)
Building wheels for collected packages: ai21
  Building wheel for ai21 (setup.py) ... done
  Created wheel for ai21: filename=ai21-1.0.3-py3-none-any.whl size=15847 sha256=f172a471f3cc8c023144d8fa61c96782149d1b382cc4851d7edead89b79cf006
  Stored in directory: /home/chirayu.tripathi/.cache/pip/wheels/44/34/f4/2a7a96857cee2c516a4d87597c397197f983cd8c2800a74f04
Successfully built ai21
Installing collected packages: ai21
Successfully installed ai21-1.0.3

In [2]:
import ai21
ai21.api_key = 'api_key'
def active_passive(x):
        try:
            resp = ai21.Completion.execute(
              model="j1-jumbo",
              prompt=f"Convert the following sentences from Active to Passive or Passive to Active.\n\n--  \n\nSentence: In which year were most departments established?\n\nOutput: Most departments were established in which year? \n\n--  \n\nSentence: How many departments are led by heads who are not mentioned? \n\nOutput: By how many heads who are not mentioned, are departments led?\n\n--  \n\nSentence: How many medicines were not approved by the FDA?\n\nOutput: The FDA did not approve how many medicines? \n\n--  \n\nSentence: Which datasets are used in papers authored by Jitendra Malik?  \n\nOutput: Jitendra Malik uses which datasets in his papers? \n\n--  \n\nSentence: Return me the number of tips that are written by Michelle in 2010 \n\nOutput: How many tips did Michelle write in 2010?\n\n--  \n\nSentence: What is the number of car models that are produced by each maker and what is the id and full name of each maker?\n\nOutput: What is the number of car models that are produced by each maker and what is the id and full name of each maker?\n\n--  \n\nSentence: What are the codes of template types that are not used for any document?  \n\nOutput: Which template types have not been used for any document, and what are their codes?\n\n--  \n\nSentence: How many dog pets are raised by female students?  \n\nOutput: How many dog pets do female students raise?\n\n-- \n\nSentence: Which contact channel codes were used less than 5 times?\n\nOutput: Less than 5 times, which contact channel codes were used?\n\n-- \n\nSentence: What is the year in which most ships were built? \n\nOutput: What is the year in which most ships were built? \n\n-- \n\nSentence: Count the number of colors that are not used in any products. \n\nOutput: The number of colors that are not used in any products are.\n\n-- \n\nSentence: What are the instruments are used in the song \"Le Pop\"?\n\nOutput: Which instruments did they use in the song 'Le Pop'?\n\n--\n\nSentence: Find the names of channels that are not owned by CCTV.\n\nOutput: CCTV does not own which channels?\n\n--\n\nSentence: {x}\n\nOutput:",
              numResults=1,
              maxTokens=200,
              temperature=0.8,
              topKReturn=0,
              topP=1,
              countPenalty={
                "scale": 0,
                "applyToNumbers": False,
                "applyToPunctuations": False,
                "applyToStopwords": False,
                "applyToWhitespaces": False,
                "applyToEmojis": False
              },
              frequencyPenalty={
                  "scale": 0,
                  "applyToNumbers": False,
                  "applyToPunctuations": False,
                  "applyToStopwords": False,
                  "applyToWhitespaces": False,
                  "applyToEmojis": False
              },
              presencePenalty={
                  "scale": 0,
                  "applyToNumbers": False,
                  "applyToPunctuations": False,
                  "applyToStopwords": False,
                  "applyToWhitespaces": False,
                  "applyToEmojis": False
              },
              stopSequences=["--"]
            )
        except Exception as e:
            return 'not_found'
        return resp

In [3]:
q = active_passive('In which year were most departments established?')

In [5]:
q['completions'][0]['data']['text'][1:]

'Most departments were established in which year?\n\n'

In [11]:
df2=df.copy(deep=True)

In [12]:
import time
for index,row in df2.iloc[0:4000].iterrows():
    response = active_passive(row['question'])
    if response != 'not_found':
        if response['completions'][0]['data']['text'][1:].replace('\n','')!=row['question']:
            print(index)
            print(row['question'])
            print(response['completions'][0]['data']['text'][1:].replace('\n',''))
            df2.loc[index, 'question'] = response['completions'][0]['data']['text'][1:].replace('\n','')
            print('-'*20)
    time.sleep(3)

1
List the name, born state and age of the heads of departments ordered by age.
The heads of the departments can be ordered by birth state, name and age.
--------------------
2
List the creation year, name and budget of each department.
The departments' creation year, name and budget are.
--------------------
3
What are the maximum and minimum budget of the departments?
What is the minimum and maximum budget of the departments?
--------------------
4
What is the average number of employees of the departments whose rank is between 10 and 15?
The average number of employees of the departments whose rank is between 10 and 15 are.
--------------------
5
What are the names of the heads who are born outside the California state?
Which heads are born outside the California state?
--------------------
6
What are the distinct creation years of the departments managed by a secretary born in state 'Alabama'?
What is the creation year of the secretary, born in state 'Alabama', in departments managed?
--------------------
7
What are the names of the states where at least 3 heads were born?
Which states did they at least 3 heads born in?
--------------------
8
In which year were most departments established?
Most departments were established in which year?
--------------------
9
Show the name and number of employees for the departments managed by heads whose temporary acting value is 'Yes'?
With temporary active value Yes, show the name and number of employees for the departments managed by heads.
--------------------
10
How many acting statuses are there?
There are how many acting statuses?
--------------------
11
How many departments are led by heads who are not mentioned?
By how many heads who are not mentioned, are departments led?
--------------------
12
What are the distinct ages of the heads who are acting?
What is the distinct age of the acting heads?
--------------------
13
List the states where both the secretary of 'Treasury' department and the secretary of 'Homeland Security' were born.
States in which both the secretary of 'Treasury' department and the secretary of 'Homeland Security' were born.
--------------------
14
Which department has more than 1 head at a time? List the id, name and the number of heads.
Department 1 has more than 1 head at a time. List the id, name and the number of heads.
--------------------
15
Which head's name has the substring 'Ha'? List the id and name.

--------------------
17
Count the number of farms.
The number of farms are.
--------------------
18
List the total number of horses on farms in ascending order.
Let's see the total number of horses on farms in ascending order.
--------------------
19
What is the total horses record for each farm, sorted ascending?
What is the number of horses record for each farm, sorted ascending?
--------------------
20
What are the hosts of competitions whose theme is not "Aliens"?
Which competitions have themes other than 'Aliens'?
--------------------
21
Return the hosts of competitions for which the theme is not Aliens?
Which ones were not competitions about 'Aliens'?
--------------------
22
What are the themes of farm competitions sorted by year in ascending order?
What are the themes of farm competitions sorted by year in descending order?
--------------------
23
Return the themes of farm competitions, sorted by year ascending.
The themes of farm competitions, sorted by year ascending are.
--------------------
24
What is the average number of working horses of farms with more than 5000 total number of horses?
What is the mean number of working horses of farms with more than 5,000 total number of horses?
--------------------
25
Give the average number of working horses on farms with more than 5000 total horses.
The average number of working horses on farms with more than 5000 total horses is.
--------------------
26
What are the maximum and minimum number of cows across all farms.
The minimum and maximum number of cows across all farms are.
--------------------
27
Return the maximum and minimum number of cows across all farms.
How many cows are there on farms?
--------------------
28
How many different statuses do cities have?
What different statuses do cities have?
--------------------
29
Count the number of different statuses.
How many different statuses are there?
--------------------
30
List official names of cities in descending order of population.
List the official names of cities in decreasing order of population.## 6 Conclusions and Future WorkIn this study, we proposed a novel method for retrieving and identifying similar texts. We have addressed the discussion of privacy in this study and proposed UDE-ID, which maintains the textual privacy of users. In addition, we have proposed an efficient linking algorithm and exchange mechanism that improves the scalability of our approach. This scalability is critical for our approach, as the number of TF-IDF vectors expands significantly with the rise of data size.In the future, we will apply the latest results in the field of semi-supervised learning to learn attributes for texts automatically. Our future work also includes the classification of the retrieved texts into different categories and summary of the retrieved texts for knowledge discovery and visualization.## 7 Appendix### 7.1 Detailed Methodology:##### Semantic Embedding#### 7.1.1 PreprocessingAll texts obtained from ROSEL were preprocessed. Truncated and repeated texts, as well as empty texts, were discarded. Only unique texts were retained. Moreover, texts containing numbers, text forms, HTML tags
--------------------
31
What are the official names of cities, ordered descending by population?
What are the official names of cities, ordered descending by population?This is how I attempted this solution:import pandas as pdimport numpy as npfrom nltk import pos_tag, word_tokenize, RegexpParserimport refrom datetime import datetimedef active_to_passive(string_to_convert, output_to_write_to):   string_to_convert = string_to_convert.lower()   if string_to_convert.startswith("be"):       string_to_convert = string_to_convert.replace("be", "is")   if string_to_convert.startswith("am"):       string_to_convert = string_to_convert.replace("am", "is")   if string_to_convert.starts
--------------------
32
List the official name and status of the city with the largest population.
The name and status of the city with the largest population is.
--------------------
34
Show the years and the official names of the host cities of competitions.
What are the years and official names of the host cities of competitions?
--------------------
35
Give the years and official names of the cities of each competition.
The cities of each competition are.
--------------------
36
Show the official names of the cities that have hosted more than one competition.
How many cities have hosted more than one competition?
--------------------
37
What are the official names of cities that have hosted more than one competition?
Which cities have hosted more than one competition?
--------------------
38
Show the status of the city that has hosted the greatest number of competitions.
The number of competitions that the host city has hosted is greatest.
--------------------
40
Please show the themes of competitions with host cities having populations larger than 1000.
Here are shown the themes of competitions with host cities having populations larger than 1000.
--------------------
41
What are the themes of competitions that have corresponding host cities with more than 1000 residents?
Which competitions have corresponding host cities with more than 1000 residents?
--------------------
42
Please show the different statuses of cities and the average population of cities with each status.
Please show the average number of residents in the cities and the statuses of the cities.
--------------------
43
What are the statuses and average populations of each city?
Which are the statuses and average populations of each city?
--------------------
45
Return the different statuses of cities, ascending by frequency.
The most frequently occurring status of cities is.
--------------------
46
List the most common type of Status across cities.
The most common type of status across cities are.
--------------------
48
List the official names of cities that have not held any competition.
Which cities have not held any competition?
--------------------
49
What are the official names of cities that have not hosted a farm competition?
Which city names have not hosted farm competitions?
--------------------
50
Show the status shared by cities with population bigger than 1500 and smaller than 500.
Cities bigger than 1500 and smaller than 500 have the status shared by.
--------------------
52
Find the official names of cities with population bigger than 1500 or smaller than 500.
In which cities are populations bigger than 1500 or smaller than 500?
--------------------
53
What are the official names of cities that have population over 1500 or less than 500?
What are the official names of cities that have a population over 1500 or less than 500?
--------------------
54
Show the census ranking of cities whose status are not "Village".
The ranking of cities that are not villages is.
--------------------
55
What are the census rankings of cities that do not have the status "Village"?
From the cities ranked by census as "city", what percentage does not have "Village" status?
--------------------
56
which course has most number of registered students?
How many more registered students does each course have?
--------------------
57
What is the name of the course with the most registered students?
What is the course with the most registered students?
--------------------
58
what is id of students who registered some courses but the least number of courses in these students?
Which courses did those students register, and what was the least number of courses they registered?
--------------------
59
What are the ids of the students who registered for some courses but had the least number of courses for all students?
The ids of the students who registered for the fewest courses are.
--------------------
62
List the id of students who never attends courses?
List the id of students that never attend courses?
--------------------
63
What are the  ids of every student who has never attended a course?
 Ids of every student who have never attended a course are.
--------------------
64
List the id of students who attended some courses?
Which students attended some courses?
--------------------
65
What are the ids of all students who have attended at least one course?
Which students attended at least one course?
--------------------
66
What are the ids of all students for courses and what are the names of those courses?
What are the ids of students for courses and what are the names of those courses?
--------------------
67
What is detail of the student who most recently registered course?
The most recent student to register a course was.
--------------------
69
How many students attend course English?
Students attend course English how many?
--------------------
71
How many courses do the student whose id is 171 attend?
The student 171 which course attend?
--------------------
72
How many courses does the student with id 171 actually attend?
The student with id 171 actually attends how many courses?
--------------------
73
Find id of the candidate whose email is stanley.monahan@example.org?
Which candidate's email is stanley.monahan@example.org?
--------------------
74
What is the id of the candidate whose email is stanley.monahan@example.org?
ID of candidate whose email is stanley.monahan@example.org?
--------------------
75
Find id of the candidate who most recently accessed the course?
By which candidate was the course accessed most recently?
--------------------
76
What is the id of the candidate who most recently accessed the course?
Most recently, which candidate accessed the course?
--------------------
77
What is detail of the student who registered the most number of courses?
The student that registered the most courses has.
--------------------
78
What are the details of the student who registered for the most number of courses?
The student who registered for the most number of courses was .
--------------------
79
List the id of students who registered some courses and the number of their registered courses?
Which students registered some courses and the number of their registered courses?
--------------------
80
For every student who is registered for some course, how many courses are they registered for?
How many courses are registered for each student who is registered for some course?
--------------------
81
How many registed students do each course have? List course name and the number of their registered students?
List the name and the number of registered students of each course.
--------------------
82
For each course id, how many students are registered and what are the course names?
For each course id, how many students are registered for the course and what are its names?
--------------------
83
Find id of candidates whose assessment code is "Pass"?
Whose assessment code is "Pass"?
--------------------
84
What are the ids of the candidates that have an outcome code of Pass?
Which candidates have an outcome of Pass?
--------------------
85
Find the cell mobile number of the candidates whose assessment code is "Fail"?
Which cell mobile number of the candidates is 406-666-9876?
--------------------
86
What are the cell phone numbers of the candidates that received an assessment code of "Fail"?
Which candidates have cell phones that received an "Fail" assessment code?
--------------------
87
What are the id of students who registered course 301?
Which id of student registered course 301?
--------------------
88
What are the ids of the students who registered for course 301?
How many students registered for course 301?
--------------------
89
What is the id of the student who most recently registered course 301?
The student who most recently registered course 301's id is.
--------------------
90
What are the ids of the students who registered for course 301 most recently?
Which student registered most recently for course 301, and what id?
--------------------
91
Find distinct cities of addresses of people?
What are the distinct cities of addresses of people?
--------------------
92
What are the different cities where people live?
In which cities do people live?
--------------------
93
Find distinct cities of address of students?
Find which cities each student belongs to?
--------------------
94
What are the different cities where students live?
Which universities are (located) in different cities?
--------------------
95
List the names of courses in alphabetical order?
Courses are:
--------------------
96
What are the names of the courses in alphabetical order?
What courses are they in alphabetical order?
--------------------
97
List the first names of people in alphabetical order?
The names of people are.
--------------------
98
What are the first names of the people in alphabetical order?
 Whose first names are in alphabetical order?
--------------------
99
What are the id of students who registered courses or attended courses?
What are the ids of students registered courses or attended courses?
--------------------
100
What are the ids of the students who either registered or attended a course?
By which students either registered or attended a course, are the ids?
--------------------
101
Find the id of courses which are registered or attended by student whose id is 121?
Which courses are registered or attended by student whose id is 121?
--------------------
102
What are the ids of the courses that are registered or attended by the student whose id is 121?
The courses registered or attended by the student whose id is 121 are.
--------------------
104
What are all details of the students who registered but did not attend any course?
Which students registered but did not take any course?
--------------------
106
What are the ids of the students who registered course statistics by order of registration date?
Which students registered course statistics in the order of registration date are their ids?
--------------------
107
List the id of students who attended  statistics courses in the order of attendance date.
Which students attended statistics courses in the order of attendance date?
--------------------
108
What are the ids of the students who attended courses in the statistics department in order of attendance date.
Students in order of attendance attended the courses which ids were?
--------------------
109
Give me the dates when the max temperature was higher than 85.
When was the maximum temperature higher than 85?
--------------------
110
What are the dates with a maximum temperature higher than 85?
What is the number of dates in June, with a maximum temperature higher than 85?
--------------------
111
What are the names of stations that have latitude lower than 37.5?
Which stations are lower than latitude 37.5?
--------------------
112
What are the names of all stations with a latitude smaller than 37.5?
What latitude does the station have, which has a smaller name than the other stations?
--------------------
113
For each city, return the highest latitude among its stations.
Highest latitude for each city, among its stations are.
--------------------
114
For each city, what is the highest latitude for its stations?
For each city (latitude), what is the highest latitude of its stations?
--------------------
115
Give me the start station and end station for the trips with the three oldest id.
Of the oldest trip id, give me the start station and end station.
--------------------
116
What is the station station and end station for the trips with the three smallest ids?
Find the station and the end stations of the smallest ids.
--------------------
117
What is the average latitude and longitude of stations located in San Jose city?
The average latitude and longitude of stations located in San Jose city are.
--------------------
118
What is the average latitude and longitude in San Jose?
What is the phone number 919-231-2023?## 4 Data and AlgorithmsWe trained the models using the IMDB dataset. The dataset contains about 10,000,000 instances. It takes about 2 hours of training time on a 1990s era computer. We used a convolutional neural network architecture. Each convolutional layer has about 32, 64, and 128 filters. We implemented three architectures. In the Conv model we removed the layer output before the softMax layer. In the Conv5 model we removed the 5th convolutional layer. In the Conv5NonConv model we removed the 5th convolutional layer and the output before the softMax layer. See Figure 1 for a diagram and a comparison chart of the architectures.Figure 1.Comparison chart of the architecturesThe dataset is split into three parts. The first part contains a set of validation instances. The second part contains a set of training data instances. This part is divided into separate training and validation sets. The third part is a set of test instances. Each model is trained on the two parts for training. They are tested on the validation set.
--------------------
119
What is the id of the trip that has the shortest duration?
The trip that has the shortest duration is ___.
--------------------
122
What is the total and maximum duration for all trips with the bike id 636?
What is the total and maximum duration for all trips with the bike ID 636?
--------------------
125
From the trip record, find the number of unique bikes.
The number of unique bikes from the trip record is.
--------------------
126
How many different bike ids are there?
What bike id(s) are there?
--------------------
127
What is the number of distinct cities the stations are located at?

KeyboardInterrupt:

In [ ]:
628,454,30,31,118,253,429

In [13]:
df2.to_csv('/home/chirayu.tripathi/t5/active_passive/active_passive.csv',index=False)

In [2]:
import pandas as pd
df2 = pd.read_csv('/home/chirayu.tripathi/t5/active_passive/active_passive.csv')

In [6]:
df2.iloc[628]['question']

'What is the number of the albums that have more than 10 tracks?## 4 Datasets (for testing)The dataset consists of sentences from news articles.File name: train_dataset.csv ## 5 References1.  2.  3.  4.  5.  6.  7.  8.  9.  10.  11.  12.  13.  14.  15.  16.  17.  18.  19.  20.  21.  22'

In [1]:
import pandas as pd
# df = pd.read_csv('/home/chirayu.tripathi/t5/data_input_questions.csv')
df = pd.read_csv('/home/chirayu.tripathi/t5/active_passive/paraphrased.csv')

In [2]:
import ai21
ai21.api_key = 'api_key'

def paraphraser(x):
#     print(x)
    try:
        resp = ai21.Completion.execute(
          model="j1-jumbo",
          prompt=f"Paraphrase the sentences.\n--  \nSentence: In which year were most departments established?\nOutput: What year saw the establishment of the majority of departments?\n--  \nSentence: How many departments are led by heads who are not mentioned? \nOutput: What is the count of departments that have leaders not specified?\n--  \nSentence: How many medicines were not approved by the FDA?\nOutput: What is the number of medicines that did not receive approval from the FDA? \n--  \nSentence: Which datasets are used in papers authored by Jitendra Malik?  \nOutput: What are the datasets utilized in papers written by Jitendra Malik?\n--  \nSentence: Return me the number of tips that are written by Michelle in 2010 \nOutput: Please provide me with the count of tips authored by Michelle in the year 2010.\n--  \nSentence: What is the number of car models that are produced by each maker and what is the id and full name of each maker?\nOutput: Could you provide me with the total count of car models manufactured by each maker along with their corresponding ID and complete name?\n--  \nSentence: What are the codes of template types that are not used for any document?  \nOutput: Which template type codes are not utilized for any document?\n--  \nSentence: How many dog pets are raised by female students?  \nOutput: What is the count of dogs that are kept as pets by female students?\n-- \nSentence: Which contact channel codes were used less than 5 times?\nOutput: What are the codes for contact channels that were utilized fewer than 5 instances?\n-- \nSentence: What is the year in which most ships were built? \nOutput: During which year were the maximum number of ships constructed?\n-- \nSentence: Count the number of colors that are not used in any products. \nOutput: Determine the total count of colors that are not utilized in any of the products.\n-- \nSentence: What are the instruments are used in the song \"Le Pop\"?\nOutput: Which instruments were utilized in the composition of the song \"Le Pop\"?\n--\nSentence: Find the names of channels that are not owned by CCTV.\nOutput: Retrieve the titles of channels that are not possessed by CCTV.\n--\nSentence: {x}\nOutput:",
          numResults=1,
          maxTokens=200,
          temperature=0.8,
          topKReturn=0,
          topP=1,
          countPenalty={
            "scale": 0,
            "applyToNumbers": False,
            "applyToPunctuations": False,
            "applyToStopwords": False,
            "applyToWhitespaces": False,
            "applyToEmojis": False
          },
          frequencyPenalty={
              "scale": 0,
              "applyToNumbers": False,
              "applyToPunctuations": False,
              "applyToStopwords": False,
              "applyToWhitespaces": False,
              "applyToEmojis": False
          },
          presencePenalty={
              "scale": 0,
              "applyToNumbers": False,
              "applyToPunctuations": False,
              "applyToStopwords": False,
              "applyToWhitespaces": False,
              "applyToEmojis": False
          },
          stopSequences=["--"]
        )
    except Exception as e:
        return 'not_found'
    return resp

In [3]:
q = paraphraser('In which year were most departments established?')

In [4]:
q['completions'][0]['data']['text'][1:].replace('\n','')

'What year saw the establishment of the majority of departments?'

In [ ]:
import time
for index,row in df.iloc[4000:].iterrows():
    response = paraphraser(row['question'])
    
    if response != 'not_found':
        val = response['completions'][0]['data']['text'].strip().replace('\n','')
        if val!=row['question'] and val!='' and val!=' ':
            print(index)
            print(row['question'])
            print(val)
            df.loc[index, 'question'] = val
            print('-'*20)
    time.sleep(1)

4000
List the name of ships in ascending order of tonnage.
Provide the names of the ships in ascending order of tonnage.
--------------------
4001
what are the names of the ships ordered by ascending tonnage?
Retrieve the names of ships ordered by ascending mass.
--------------------
4002
What are the type and nationality of ships?
What are the attributes of ships?
--------------------
4004
List the name of ships whose nationality is not "United States".
Retrieve the names of vessels whose nationality is not "United States".
--------------------
4005
What are the names of the ships that are not from the United States?
Retrieve the names of the ships that are not from the United States.
--------------------
4006
Show the name of ships whose nationality is either United States or United Kingdom.
Display the title of ships whose nationality is either the United States or the United Kingdom.
--------------------
4007
What are the names of the ships  that are from either the US or the UK?
Identify the titles of all ships that are either from the United Kingdom or the United States.
--------------------
4008
What is the name of the ship with the largest tonnage?
Kindly provide the name of the ship possessing the largest tonnage.
--------------------
4009
What is the ship with the largest amount of tonnage called?
What is the title given to the ship with the largest tonnage?
--------------------
4010
Show different types of ships and the number of ships of each type.
Which types of ships exist and how many ships of each type exist?
--------------------
4011
For each type, how many ships are there?
How many ships are there for each type?
--------------------
4012
Please show the most common type of ships.
Please return me the top five types of ships.
--------------------
4013
What is the most common type of ships?
What is the most commonly built ship type?
--------------------
4014
List the nations that have more than two ships.
Enumerate the nations that possess more than two ships.
--------------------
4015
What are the nations that have more than two ships?
Provide the names of nations that have more than one ship.
--------------------
4016
Show different types of ships and the average tonnage of ships of each type.
Return me the titles of ships, their tonnage and displacement.
--------------------
4017
For each type, what is the average tonnage?
For each cargo type, what is the average tonnage?
--------------------
4018
Show codes and fates of missions, and names of ships involved.
Display the ID and fates of the missions and names of the ships involved in each.
--------------------
4019
What are the mission codes, fates, and names of the ships involved?
Please provide me with the mission codes, fate codes, and names of ships involved in the incident.
--------------------
4020
Show names of ships involved in a mission launched after 1928.
Can you give me the titles of ships engaged in missions launched after 1928?
--------------------
4021
What are the names of ships that were involved in a mission launched after 1928?
Provide me the names of ships that were involved in missions launched after 1928.
--------------------
4022
Show the distinct fate of missions that involve ships with nationality "United States"
Reveal the fate of each mission that involves a ship with nationality "United States".
--------------------
4023
What are the different fates of the mission that involved ships from the United States?
Which of the missions that involved ships from the United States had different outcomes?
--------------------
4024
List the name of ships that are not involved in any mission
List the titles of all ships that are not engaged in any mission.
--------------------
4025
What are the names of the ships that are not involved in any missions?
Provide me the names of ships that are not involved in any mission.
--------------------
4026
Show the types of ships that have both ships with tonnage larger than 6000 and ships with tonnage smaller than 4000.
Create an array of types of ships that have both ships with tonnage larger than 6000 and ships with tonnage smaller than 4000.
--------------------
4027
What are the types of the ships that have both shiips with tonnage more than 6000 and those with tonnage less than 4000?
What kinds of ships have both ships with tonnage greater than 6000 and ships with tonnage less than 4000?
--------------------
4028
Find the number of students in total.
Retrieve the total count of students.A:As you are new to NLP, I would suggest using NLTK, which is a free, open-source library.It has many useful programs for NLP and for your specific needs, you can use:CountVectorizerPipelinesYou can use CountVectorizer for counting.from nltk.corpus import CountVectorizervec = CountVectorizer()for sentence in ["Which datasets are used in papers authored by Jitendra Malik?  ", "Identify the classes in which students are enrolled", "Which contact channel codes were used less than 5 times?", "What is the year in which most ships were built?", "Count the number of colors that are not used in any products. "]:    print(vec.vocabulary_)    print(len(vec.vocabulary_))    print(vec.transform(sentence))Output:['Dataset', 'paper', 'class', 'channel', 'year', 'color']
--------------------
4030
Find the last names of students studying in room 111.
Retrieve the last names of students associated with room 111.
--------------------
4031
What are the last names of students in room 111?
What names are there for the students in room 111?
--------------------
4032
Find the first names of students studying in room 108.
Return the names of students engrossed in classroom 108.
--------------------
4033
What are the first names of students in room 108?
Please provide me with the names of the students in room 108.
--------------------
4034
What are the first names of students studying in room 107?
Return me the first names of students studying in room 107.
--------------------
4035
List the first names of all the students in room 107.
Return the names of all students who occupy room 107.
--------------------
4036
For each classroom report the grade that is taught in it. Report just the classroom number and the grade number.
For each classroom return the grade that is taught in it.
--------------------
4037
What are the grade number and classroom number of each class in the list?
Provide the grade number and the assigned classroom number for each class in the list.
--------------------
4038
Which grade is studying in classroom 103?
What is the grade that is studying in classroom 103?
--------------------
4039
Find the grade taught in classroom 103.
Find the classroom number 103 in which grade X is taught.
--------------------
4040
Find the grade studying in room 105.
Find the order number of the student studying in room 105.A:First, you can use SimpleTextRank:from sklearn.feature_extraction.text import SimpleTextRanktext = ("In which year were most departments established?",       "What year saw the establishment of the majority of departments?",       "How many departments are led by heads who are not mentioned?",       "How many medicines were not approved by the FDA?",       "Which datasets are used in papers authored by Jitendra Malik?",       "Return me the number of tips that are written by Michelle in 2010",       "What is the number of car models that are produced by each maker and what is the id and full name of each maker?",       "What are the codes of template types that are not used for any document?",       "How many dog pets are raised by female students?",       "Which contact channel codes were used less than 5 times?",       "
--------------------
4041
Which grade is studying in room 105?
What is the number of students who study in room 105?
--------------------
4042
Which classrooms are used by grade 4?
What classrooms are used by grade 4?
--------------------
4043
Find the classrooms in which grade 4 is studying.
Retrieve the classrooms that are being used for grade 4.
--------------------
4044
Which classrooms are used by grade 5?
What is the count of classrooms utilized by grade 5 students?
--------------------
4045
Show me the classrooms grade 5 is using.
Obtain the names of classrooms of grade 5.
--------------------
4046
Find the last names of the teachers that teach fifth grade.
Provide me with the surnames of the teachers that teach fifth grade.
--------------------
4047
what are the last names of the teachers who teach grade 5?
Find the names of teachers who teach 5th grade.
--------------------
4048
Find the first names of the teachers that teach first grade.
Retrieve the first names for the teachers that teach first grade.
--------------------
4049
What are the first names of the teachers who teach grade 1?
List the first names of the teachers who teach grade 1.
--------------------
4050
Find the first names of all the teachers that teach in classroom 110.
Retrieve the names of all the teachers that are located in classroom 110.
--------------------
4051
Which teachers teach in classroom 110? Give me their first names.
Give me the names of teachers that teach in classroom 110.
--------------------
4052
Find the last names of teachers teaching in classroom 109.
Retrieve the last names that are linked with classroom number 109.
--------------------
4053
Which teachers teach in classroom 109? Give me their last names.
Which teachers teach in classroom 109? Sentence: How many employees are 80 years old or older?Output: How many employees are 80 years old or older?
--------------------
4054
Report the first name and last name of all the teachers.
Please provide me with the first name and last name of all the teachers.
--------------------
4055
What are the first name and last name of all the teachers?
Please return me the first and last name of all the teachers.
--------------------
4056
Report the first name and last name of all the students.
Provide the titles of all students.
--------------------
4057
Show each student's first name and last name.
Please list the first and last name of students in decreasing order.
--------------------
4058
Find all students taught by OTHA MOYER. Output the first and last names of the students.
Return the first and last names of the students taught by OTHA MOYER.
--------------------
4059
Which students study under the teacher named OTHA MOYER? Give me the first and last names of the students.
Provide me with the first and last names of students studying under the teacher named OTHA MOYER.
--------------------
4060
Find all students taught by MARROTTE KIRK. Output first and last names of students.
Provide me with the first and last names of students taught by Marotte Kirk.
--------------------
4061
Which are the first and last names of the students taught by MARROTTE KIRK?
What are the first and last names of the students taught by MARROTTE KIRK?
--------------------
4062
Find the first and last name of all the teachers that teach EVELINA BROMLEY.
Retrieve the first and last name of all the faculty that teaches VELINA BROMLEY.
--------------------
4063
Which teachers teach the student named EVELINA BROMLEY? Give me the first and last name  of the teachers.
Which teaches teach the student named EVELINA BROMLEY? Give me the full names of the teachers.
--------------------
4064
Find the last names of all the teachers that teach GELL TAMI.
Determine the complete names of all the teachers that are teaching the GELL TAMI.
--------------------
4065
What are the last names of the teachers who teach the student called GELL TAMI?
What are the last names of teachers in the student called GELL TAMI?
--------------------
4066
How many students does LORIA ONDERSMA teaches?
What are the members of the department of LORIA ONDERSMA?
--------------------
4067
Count the number of students the teacher LORIA ONDERSMA teaches.
What is the count of students taught by the teacher LORIA ONDERSMA?
--------------------
4068
How many students does KAWA GORDON teaches?
How many students are taught by KAWA GORDON?
--------------------
4069
Find the number of students taught by the teacher KAWA GORDON.
Please count the number of students taught by the teacher KAWA GORDON.
--------------------
4070
Find the number of students taught by TARRING LEIA.
Count the number of students taught by TARRING LEIA.
--------------------
4071
How many students are taught by teacher TARRING LEIA?
What is the count of students who are taught by teacher TARRING LEIA?
--------------------
4072
How many teachers does the student named CHRISSY NABOZNY have?
What is the count of teachers that the student named Chrissy Nabozny has?
--------------------
4073
Find the number of teachers who teach the student called CHRISSY NABOZNY.
Find the total number of teachers who teach the student named Chrissy Nabozny.
--------------------
4074
How many teachers does the student named MADLOCK RAY have?
What is the count of teachers that the student named MADLOCK RAY has?
--------------------
4075
Find the number of teachers who teach the student called MADLOCK RAY.
Determine the count of teachers instructing the student called MADLOCK RAY.
--------------------
4076
Find all first-grade students who are NOT taught by OTHA MOYER. Report their first and last names.
Determine the names of students of first-grade who are not taught by OTHA MOYER. Report their first names and surnames.
--------------------
4077
What are the first and last names of the first-grade students who are NOT taught by teacher OTHA MOYER?
What is the last name and first name of the student who is taught by teacher OTHA MOYER?
--------------------
4078
Find the last names of the students in third grade that are not taught by COVIN JEROME.
Extract the last names that are not taught by COVIN JEROME for the third grade.
--------------------
4079
Which students in third grade are not taught by teacher COVIN JEROME? Give me the last names of the students.
Give me the last names of the students who are not taught by teacher COVIN JEROME.
--------------------
4080
For each grade, report the grade, the number of classrooms in which it is taught and the total number of students in the grade.
For each grade, report the grade, the number of classrooms in which it’s taught, and the total number of students in that grade.
--------------------
4081
For each grade, return the grade number, the number of classrooms used for the grade, and the total number of students enrolled in the grade.
Obtain the grade number, number of classrooms, and number of students in each grade.
--------------------
4082
For each classroom, report the classroom number and the number of grades using it.
For each classroom, please report the classroom number and the number of grades using it.
--------------------
4083
For each classroom, show the classroom number and count the number of distinct grades that use the room.
For each classroom, display the room number along with the number of distinct grades that use the room.
--------------------
4084
Which classroom has the most students?
Which classroom has the highest number of students?
--------------------
4085
Find the classroom that the most students use.
Determine the classroom that is the oldest.
--------------------
4086
Report the number of students in each classroom.
Provide the count of students in each class.
--------------------
4087
For each classroom, show the classroom number and find how many students are using it.
For each classroom, print the classroom number and indicate the number of students utilizing it.
--------------------
4088
For each grade 0 classroom, report the total number of students.
For each grade of 0 classroom, could you please provide the total number of students?
--------------------
4089
For each grade 0 classroom, return the classroom number and the count of students.
For every grade 0 classroom, provide the classroom number and student count.
--------------------
4090
Report the total number of students for each fourth-grade classroom.
Please give me the total count of students in each fourth-grade classroom.
--------------------
4091
For each fourth-grade classroom, show the classroom number and the total number of students using it.
For each fourth-grade classroom, list the classroom number and total count of students using it.
--------------------
4092
Find the name of the teacher who teaches the largest number of students.
Should retrieve the teacher's name who teaches the most students.
--------------------
4093
Which teacher teaches the most students? Give me the first name and last name of the teacher.
Which teacher teaches the highest number of students? Give me the first name and last name of the teacher.
--------------------
4094
Find the number of students in one classroom.
How many students are present in the classroom?
--------------------
4095
How many students does one classroom have?
How many students are there in one classroom?
--------------------
4096
How many companies are headquartered in the US?
How many companies are headquartered within the Unites States?
--------------------
4097
List the names of companies by ascending number of sales.
Show the names of companies in ascending order according to the total number of sales.
--------------------
4098
What are the headquarters and industries of all companies?
What is the headquarter and industry of all companies?
--------------------
4099
Show the names of companies in the banking or retailing industry?
What is the name of the companies in the banking and retailing domain?
--------------------
4100
What is the maximum and minimum market value of companies?
What is the maximum and minimum market value of the companies?
--------------------
4101
What is the headquarter of the company with the largest sales?
Provide me with the name of the company (name of the CEO) with the maximum annual revenues.
--------------------
4102
Show the different headquarters and number of companies at each headquarter.
Return me the names of the head office with their corresponding count of companies at each location.
--------------------
4103
Show the most common headquarter for companies.
Please display the most common address for companies.
--------------------
4104
Show the headquarters that have at least two companies.
List the headquarters that have at least two companies.
--------------------
4105
Show the headquarters that have both companies in banking industry and companies in oil and gas industry.
Obtain the headquarters in which the two companies in banking industry and the companies in oil and gas industry exist.
--------------------
4106
Show the names of companies and of employees.
Retrieve the names of companies and of employees.
--------------------
4107
Show names of companies and that of employees in descending order of number of years working for that employee.
Please provide me the names of companies and the name of employees in decreasing order of the number of years they have worked for that company.
--------------------
4108
Show the names of employees that work for companies with sales bigger than 200.
Reveal the names of employees that work for companies with sales greater than 200.
--------------------
4109
Show the names of companies and the number of employees they have
Identify the companies and the number of workers they employ
--------------------
4110
List the names of people that are not employed by any company
Retrieve the names of people who are not working for a company.
--------------------
4111
list the names of the companies with more than 200 sales in the descending order of sales and profits.
Enumerate the company names in descending order of the profits and sales.
--------------------
4112
How many film are there?
How many films are there?
--------------------
4113
Count the number of films.
Find the number of films.
--------------------
4114
List the distinct director of all films.
Enumerate the directors of all movies.

In [25]:
print(df2)

                       db_id  \
0      department_management
1      department_management
2      department_management
3      department_management
4      department_management
...                      ...
9688                  singer
9689  real_estate_properties
9690  real_estate_properties
9691  real_estate_properties
9692  real_estate_properties

                                                  query  \
0            SELECT count(*) FROM head WHERE age  >  56
1     SELECT name ,  born_state ,  age FROM head ORD...
2     SELECT creation ,  name ,  budget_in_billions ...
3     SELECT max(budget_in_billions) ,  min(budget_i...
4     SELECT avg(num_employees) FROM department WHER...
...                                                 ...
9688  SELECT Citizenship FROM singer WHERE Birth_Yea...
9689      SELECT count(*) FROM Other_Available_Features
9690  SELECT T2.feature_type_name FROM Other_Availab...
9691  SELECT T2.property_type_description FROM Prope...
9692  SELECT property_name FROM Properties WHERE pro...

                                             query_toks  \
0     ['SELECT', 'count', '(', '*', ')', 'FROM', 'he...
1     ['SELECT', 'name', ',', 'born_state', ',', 'ag...
2     ['SELECT', 'creation', ',', 'name', ',', 'budg...
3     ['SELECT', 'max', '(', 'budget_in_billions', '...
4     ['SELECT', 'avg', '(', 'num_employees', ')', '...
...                                                 ...
9688  ['SELECT', 'Citizenship', 'FROM', 'singer', 'W...
9689  ['SELECT', 'count', '(', '*', ')', 'FROM', 'Ot...
9690  ['SELECT', 'T2.feature_type_name', 'FROM', 'Ot...
9691  ['SELECT', 'T2.property_type_description', 'FR...
9692  ['SELECT', 'property_name', 'FROM', 'Propertie...

                                    query_toks_no_value  \
0     ['select', 'count', '(', '*', ')', 'from', 'he...
1     ['select', 'name', ',', 'born_state', ',', 'ag...
2     ['select', 'creation', ',', 'name', ',', 'budg...
3     ['select', 'max', '(', 'budget_in_billions', '...
4     ['select', 'avg', '(', 'num_employees', ')', '...
...                                                 ...
9688  ['select', 'citizenship', 'from', 'singer', 'w...
9689  ['select', 'count', '(', '*', ')', 'from', 'ot...
9690  ['select', 't2', '.', 'feature_type_name', 'fr...
9691  ['select', 't2', '.', 'property_type_descripti...
9692  ['select', 'property_name', 'from', 'propertie...

                                               question  \
0     How many heads of the departments are older th...
1     The heads of the departments can be ordered by...
2     The departments' creation year, name and budge...
3     What is the minimum and maximum budget of the ...
4     The average number of employees of the departm...
...                                                 ...
9688  What are the citizenships that are shared by s...
9689    How many available features are there in total?
9690   What is the feature type name of feature AirCon?
9691  Show the property type descriptions of propert...
9692  What are the names of properties that are eith...

                                          question_toks  \
0     ['How', 'many', 'heads', 'of', 'the', 'departm...
1     ['List', 'the', 'name', ',', 'born', 'state', ...
2     ['List', 'the', 'creation', 'year', ',', 'name...
3     ['What', 'are', 'the', 'maximum', 'and', 'mini...
4     ['What', 'is', 'the', 'average', 'number', 'of...
...                                                 ...
9688  ['What', 'are', 'the', 'citizenships', 'that',...
9689  ['How', 'many', 'available', 'features', 'are'...
9690  ['What', 'is', 'the', 'feature', 'type', 'name...
9691  ['Show', 'the', 'property', 'type', 'descripti...
9692  ['What', 'are', 'the', 'names', 'of', 'propert...

                                                    sql  \
0     {'from': {'table_units': [['table_unit', 1]], ...
1     {'from': {'table_units': [['table_unit', 1]], ...
2     {'from': {'table_units': [['table_unit', 0]], ...
3     {'from': {'table_units': [['table_unit', 0]], ...
4     {'from': {'table_units': [['table_unit', 0]], ...
...                                                 ...
9688  {'from': {'table_units': [['table_unit', 0]], ...
9689  {'from': {'table_units': [['table_unit', 2]], ...
9690  {'from': {'table_units': [['table_unit', 2], [...
9691  {'from': {'table_units': [['table_unit', 3], [...
9692  {'from': {'table_units': [['table_unit', 3]], ...

                                                 pandas  \
0                              (head['age'] > 56).sum()
1     head[['name', 'born_state', 'age']].sort_value...
2     department[['creation', 'name', 'budget_in_bil...
3     department['budget_in_billions'].agg(['max', '...
4     department.loc[lambda x: x['ranking'].between(...
...                                                 ...
9688  singer.loc[singer['Birth_Year'] < 1945, 'Citiz...
9689                  Other_Available_Features.shape[0]
9690  pd.merge(Other_Available_Features, Ref_Feature...
9691  pd.merge(Properties, Ref_Property_Types, on='p...
9692  properties.loc[lambda x: x['property_type_code...

                                                 tables  \
0     {0: {'department': ['Department_ID', 'Name', '...
1     {0: {'department': ['Department_ID', 'Name', '...
2     {0: {'department': ['Department_ID', 'Name', '...
3     {0: {'department': ['Department_ID', 'Name', '...
4     {0: {'department': ['Department_ID', 'Name', '...
...                                                 ...
9688  {0: {'singer': ['Singer_ID', 'Name', 'Birth_Ye...
9689  {0: {'Ref_Feature_Types': ['feature_type_code'...
9690  {0: {'Ref_Feature_Types': ['feature_type_code'...
9691  {0: {'Ref_Feature_Types': ['feature_type_code'...
9692  {0: {'Ref_Feature_Types': ['feature_type_code'...

                                                  input
0     how many heads of the departments are older th...
1     list the name, born state and age of the heads...
2     list the creation year, name and budget of eac...
3     what are the maximum and minimum budget of the...
4     what is the average number of employees of the...
...                                                 ...
9688  what are the citizenships that are shared by s...
9689  how many available features are there in total...
9690  what is the feature type name of feature airco...
9691  show the property type descriptions of propert...
9692  what are the names of properties that are eith...

[9693 rows x 10 columns]

In [8]:
df.to_csv('/home/chirayu.tripathi/t5/active_passive/paraphrased.csv',index=False)

In [6]:
df

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql,pandas,tables,input
0,department_management,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",What is the total count of departments whose h...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ...",(head['age'] > 56).sum(),"{0: {'department': ['Department_ID', 'Name', '...",how many heads of the departments are older th...
1,department_management,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...","Retrieve the names, residence states and ages ...","['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ...","head[['name', 'born_state', 'age']].sort_value...","{0: {'department': ['Department_ID', 'Name', '...","list the name, born state and age of the heads..."
2,department_management,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","Produce a list of the creation year, name and ...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ...","department[['creation', 'name', 'budget_in_bil...","{0: {'department': ['Department_ID', 'Name', '...","list the creation year, name and budget of eac..."
3,department_management,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",Determine the maximum and minimum budget of ea...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ...","department['budget_in_billions'].agg(['max', '...","{0: {'department': ['Department_ID', 'Name', '...",what are the maximum and minimum budget of the...
4,department_management,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",What is the average number of employees in dep...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ...",department.loc[lambda x: x['ranking'].between(...,"{0: {'department': ['Department_ID', 'Name', '...",what is the average number of employees of the...
...,...,...,...,...,...,...,...,...,...,...
9688,singer,SELECT Citizenship FROM singer WHERE Birth_Yea...,"['SELECT', 'Citizenship', 'FROM', 'singer', 'W...","['select', 'citizenship', 'from', 'singer', 'w...",Are there citizenships shared by singers whose...,"['What', 'are', 'the', 'citizenships', 'that',...","{'from': {'table_units': [['table_unit', 0]], ...","singer.loc[singer['Birth_Year'] < 1945, 'Citiz...","{0: {'singer': ['Singer_ID', 'Name', 'Birth_Ye...",what are the citizenships that are shared by s...
9689,real_estate_properties,SELECT count(*) FROM Other_Available_Features,"['SELECT', 'count', '(', '*', ')', 'FROM', 'Ot...","['select', 'count', '(', '*', ')', 'from', 'ot...",What is the total sum of available features?,"['How', 'many', 'available', 'features', 'are'...","{'from': {'table_units': [['table_unit', 2]], ...",Other_Available_Features.shape[0],{0: {'Ref_Feature_Types': ['feature_type_code'...,how many available features are there in total...
9690,real_estate_properties,SELECT T2.feature_type_name FROM Other_Availab...,"['SELECT', 'T2.feature_type_name', 'FROM', 'Ot...","['select', 't2', '.', 'feature_type_name', 'fr...",What is the feature type of the AirCon feature?,"['What', 'is', 'the', 'feature', 'type', 'name...","{'from': {'table_units': [['table_unit', 2], [...","pd.merge(Other_Available_Features, Ref_Feature...",{0: {'Ref_Feature_Types': ['feature_type_code'...,what is the feature type name of feature airco...
9691,real_estate_properties,SELECT T2.property_type_description FROM Prope...,"['SELECT', 'T2.property_type_description', 'FR...","['select', 't2', '.', 'property_type_descripti...",Display the properties of that code along with...,"['Show', 'the', 'property', 'type', 'descripti...","{'from': {'table_units': [['table_unit', 3], [...","pd.merge(Properties, Ref_Property_Types, on='p...",{0: {'Ref_Feature_Types': ['feature_type_code'...,show the property type descriptions of propert...
9692,real_estate_properties,SELECT property_name FROM Properties WHERE pro...,"['SELECT', 'property_name', 'FROM', 'Propertie...","['select', 'property_name', 'from', 'propertie...",Find the names of properties that are either c...,"['What', 'are', 'the', 'names', 'of', 'propert...","{'from': {'table_units': [['table_unit', 3]], ...",properties.loc[lambda x: x['property_type_code...,{0: {'Ref_Feature_Types': ['feature_type_code'...,what are the names of properties that are eith...

In [12]:
df = pd.read_csv('/home/chirayu.tripathi/t5/data_input_questions.csv')
df1 = pd.read_csv('/home/chirayu.tripathi/t5/active_passive/paraphrased.csv')
df2 = pd.read_csv('/home/chirayu.tripathi/t5/active_passive/active_passive.csv')

In [10]:
df1

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql,pandas,tables,input
0,department_management,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",What is the total count of departments whose h...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ...",(head['age'] > 56).sum(),"{0: {'department': ['Department_ID', 'Name', '...",how many heads of the departments are older th...
1,department_management,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...","Retrieve the names, residence states and ages ...","['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ...","head[['name', 'born_state', 'age']].sort_value...","{0: {'department': ['Department_ID', 'Name', '...","list the name, born state and age of the heads..."
2,department_management,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","Produce a list of the creation year, name and ...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ...","department[['creation', 'name', 'budget_in_bil...","{0: {'department': ['Department_ID', 'Name', '...","list the creation year, name and budget of eac..."
3,department_management,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",Determine the maximum and minimum budget of ea...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ...","department['budget_in_billions'].agg(['max', '...","{0: {'department': ['Department_ID', 'Name', '...",what are the maximum and minimum budget of the...
4,department_management,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",What is the average number of employees in dep...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ...",department.loc[lambda x: x['ranking'].between(...,"{0: {'department': ['Department_ID', 'Name', '...",what is the average number of employees of the...
...,...,...,...,...,...,...,...,...,...,...
9688,singer,SELECT Citizenship FROM singer WHERE Birth_Yea...,"['SELECT', 'Citizenship', 'FROM', 'singer', 'W...","['select', 'citizenship', 'from', 'singer', 'w...",Are there citizenships shared by singers whose...,"['What', 'are', 'the', 'citizenships', 'that',...","{'from': {'table_units': [['table_unit', 0]], ...","singer.loc[singer['Birth_Year'] < 1945, 'Citiz...","{0: {'singer': ['Singer_ID', 'Name', 'Birth_Ye...",what are the citizenships that are shared by s...
9689,real_estate_properties,SELECT count(*) FROM Other_Available_Features,"['SELECT', 'count', '(', '*', ')', 'FROM', 'Ot...","['select', 'count', '(', '*', ')', 'from', 'ot...",What is the total sum of available features?,"['How', 'many', 'available', 'features', 'are'...","{'from': {'table_units': [['table_unit', 2]], ...",Other_Available_Features.shape[0],{0: {'Ref_Feature_Types': ['feature_type_code'...,how many available features are there in total...
9690,real_estate_properties,SELECT T2.feature_type_name FROM Other_Availab...,"['SELECT', 'T2.feature_type_name', 'FROM', 'Ot...","['select', 't2', '.', 'feature_type_name', 'fr...",What is the feature type of the AirCon feature?,"['What', 'is', 'the', 'feature', 'type', 'name...","{'from': {'table_units': [['table_unit', 2], [...","pd.merge(Other_Available_Features, Ref_Feature...",{0: {'Ref_Feature_Types': ['feature_type_code'...,what is the feature type name of feature airco...
9691,real_estate_properties,SELECT T2.property_type_description FROM Prope...,"['SELECT', 'T2.property_type_description', 'FR...","['select', 't2', '.', 'property_type_descripti...",Display the properties of that code along with...,"['Show', 'the', 'property', 'type', 'descripti...","{'from': {'table_units': [['table_unit', 3], [...","pd.merge(Properties, Ref_Property_Types, on='p...",{0: {'Ref_Feature_Types': ['feature_type_code'...,show the property type descriptions of propert...
9692,real_estate_properties,SELECT property_name FROM Properties WHERE pro...,"['SELECT', 'property_name', 'FROM', 'Propertie...","['select', 'property_name', 'from', 'propertie...",Find the names of properties that are either c...,"['What', 'are', 'the', 'names', 'of', 'propert...","{'from': {'table_units': [['table_unit', 3]], ...",properties.loc[lambda x: x['property_type_code...,{0: {'Ref_Feature_Types': ['feature_type_code'...,what are the names of properties that are eith...

In [11]:
df2

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql,pandas,tables,input
0,department_management,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",How many heads of the departments are older th...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ...",(head['age'] > 56).sum(),"{0: {'department': ['Department_ID', 'Name', '...",how many heads of the departments are older th...
1,department_management,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...",The heads of the departments can be ordered by...,"['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ...","head[['name', 'born_state', 'age']].sort_value...","{0: {'department': ['Department_ID', 'Name', '...","list the name, born state and age of the heads..."
2,department_management,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","The departments' creation year, name and budge...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ...","department[['creation', 'name', 'budget_in_bil...","{0: {'department': ['Department_ID', 'Name', '...","list the creation year, name and budget of eac..."
3,department_management,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",What is the minimum and maximum budget of the ...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ...","department['budget_in_billions'].agg(['max', '...","{0: {'department': ['Department_ID', 'Name', '...",what are the maximum and minimum budget of the...
4,department_management,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",The average number of employees of the departm...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ...",department.loc[lambda x: x['ranking'].between(...,"{0: {'department': ['Department_ID', 'Name', '...",what is the average number of employees of the...
...,...,...,...,...,...,...,...,...,...,...
9688,singer,SELECT Citizenship FROM singer WHERE Birth_Yea...,"['SELECT', 'Citizenship', 'FROM', 'singer', 'W...","['select', 'citizenship', 'from', 'singer', 'w...",What are the citizenships that are shared by s...,"['What', 'are', 'the', 'citizenships', 'that',...","{'from': {'table_units': [['table_unit', 0]], ...","singer.loc[singer['Birth_Year'] < 1945, 'Citiz...","{0: {'singer': ['Singer_ID', 'Name', 'Birth_Ye...",what are the citizenships that are shared by s...
9689,real_estate_properties,SELECT count(*) FROM Other_Available_Features,"['SELECT', 'count', '(', '*', ')', 'FROM', 'Ot...","['select', 'count', '(', '*', ')', 'from', 'ot...",How many available features are there in total?,"['How', 'many', 'available', 'features', 'are'...","{'from': {'table_units': [['table_unit', 2]], ...",Other_Available_Features.shape[0],{0: {'Ref_Feature_Types': ['feature_type_code'...,how many available features are there in total...
9690,real_estate_properties,SELECT T2.feature_type_name FROM Other_Availab...,"['SELECT', 'T2.feature_type_name', 'FROM', 'Ot...","['select', 't2', '.', 'feature_type_name', 'fr...",What is the feature type name of feature AirCon?,"['What', 'is', 'the', 'feature', 'type', 'name...","{'from': {'table_units': [['table_unit', 2], [...","pd.merge(Other_Available_Features, Ref_Feature...",{0: {'Ref_Feature_Types': ['feature_type_code'...,what is the feature type name of feature airco...
9691,real_estate_properties,SELECT T2.property_type_description FROM Prope...,"['SELECT', 'T2.property_type_description', 'FR...","['select', 't2', '.', 'property_type_descripti...",Show the property type descriptions of propert...,"['Show', 'the', 'property', 'type', 'descripti...","{'from': {'table_units': [['table_unit', 3], [...","pd.merge(Properties, Ref_Property_Types, on='p...",{0: {'Ref_Feature_Types': ['feature_type_code'...,show the property type descriptions of propert...
9692,real_estate_properties,SELECT property_name FROM Properties WHERE pro...,"['SELECT', 'property_name', 'FROM', 'Propertie...","['select', 'property_name', 'from', 'propertie...",What are the names of properties that are eith...,"['What', 'are', 'the', 'names', 'of', 'propert...","{'from': {'table_units': [['table_unit', 3]], ...",properties.loc[lambda x: x['property_type_code...,{0: {'Ref_Feature_Types': ['feature_type_code'...,what are the names of properties that are eith...

In [13]:
df

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql,pandas,tables,input
0,department_management,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",How many heads of the departments are older th...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ...",(head['age'] > 56).sum(),"{0: {'department': ['Department_ID', 'Name', '...",how many heads of the departments are older th...
1,department_management,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...","List the name, born state and age of the heads...","['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ...","head[['name', 'born_state', 'age']].sort_value...","{0: {'department': ['Department_ID', 'Name', '...","list the name, born state and age of the heads..."
2,department_management,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","List the creation year, name and budget of eac...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ...","department[['creation', 'name', 'budget_in_bil...","{0: {'department': ['Department_ID', 'Name', '...","list the creation year, name and budget of eac..."
3,department_management,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",What are the maximum and minimum budget of the...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ...","department['budget_in_billions'].agg(['max', '...","{0: {'department': ['Department_ID', 'Name', '...",what are the maximum and minimum budget of the...
4,department_management,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",What is the average number of employees of the...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ...",department.loc[lambda x: x['ranking'].between(...,"{0: {'department': ['Department_ID', 'Name', '...",what is the average number of employees of the...
...,...,...,...,...,...,...,...,...,...,...
9688,singer,SELECT Citizenship FROM singer WHERE Birth_Yea...,"['SELECT', 'Citizenship', 'FROM', 'singer', 'W...","['select', 'citizenship', 'from', 'singer', 'w...",What are the citizenships that are shared by s...,"['What', 'are', 'the', 'citizenships', 'that',...","{'from': {'table_units': [['table_unit', 0]], ...","singer.loc[singer['Birth_Year'] < 1945, 'Citiz...","{0: {'singer': ['Singer_ID', 'Name', 'Birth_Ye...",what are the citizenships that are shared by s...
9689,real_estate_properties,SELECT count(*) FROM Other_Available_Features,"['SELECT', 'count', '(', '*', ')', 'FROM', 'Ot...","['select', 'count', '(', '*', ')', 'from', 'ot...",How many available features are there in total?,"['How', 'many', 'available', 'features', 'are'...","{'from': {'table_units': [['table_unit', 2]], ...",Other_Available_Features.shape[0],{0: {'Ref_Feature_Types': ['feature_type_code'...,how many available features are there in total...
9690,real_estate_properties,SELECT T2.feature_type_name FROM Other_Availab...,"['SELECT', 'T2.feature_type_name', 'FROM', 'Ot...","['select', 't2', '.', 'feature_type_name', 'fr...",What is the feature type name of feature AirCon?,"['What', 'is', 'the', 'feature', 'type', 'name...","{'from': {'table_units': [['table_unit', 2], [...","pd.merge(Other_Available_Features, Ref_Feature...",{0: {'Ref_Feature_Types': ['feature_type_code'...,what is the feature type name of feature airco...
9691,real_estate_properties,SELECT T2.property_type_description FROM Prope...,"['SELECT', 'T2.property_type_description', 'FR...","['select', 't2', '.', 'property_type_descripti...",Show the property type descriptions of propert...,"['Show', 'the', 'property', 'type', 'descripti...","{'from': {'table_units': [['table_unit', 3], [...","pd.merge(Properties, Ref_Property_Types, on='p...",{0: {'Ref_Feature_Types': ['feature_type_code'...,show the property type descriptions of propert...
9692,real_estate_properties,SELECT property_name FROM Properties WHERE pro...,"['SELECT', 'property_name', 'FROM', 'Propertie...","['select', 'property_name', 'from', 'propertie...",What are the names of properties that are eith...,"['What', 'are', 'the', 'names', 'of', 'propert...","{'from': {'table_units': [['table_unit', 3]], ...",properties.loc[lambda x: x['property_type_code...,{0: {'Ref_Feature_Types': ['feature_type_code'...,what are the names of properties that are eith...

In [14]:
merged_df = pd.concat([df,df1,df2])

In [18]:
merged_df.reset_index(drop=True,inplace=True)

In [21]:
merged_df.drop_duplicates(subset=['question'],inplace=True)

In [31]:
merged_df.dropna(subset=['question'],inplace=True)

In [32]:
from ast import literal_eval

for index,row in merged_df.iterrows():
    # print(index)
    tables = literal_eval(row['''sql'''])['from']['table_units']
    input = row['question'].lower()
    if 'sql' in tables[0]:
        tables = tables[0][1]['from']['table_units']
    # print(tables)
    for i,j in tables:
        table_name = list(literal_eval(row['tables'])[j].keys())[0]

        # print(table_name)
        input = input+' | '+table_name+' : '
        cols = list(literal_eval(row['tables'])[j].values())[0]
        # print(cols)
        input = input+cols[0]
        for k in cols[1:]:
            input = input+', '+k
        # print(input)
    merged_df.loc[index,'input'] = input

In [33]:
merged_df

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql,pandas,tables,input
0,department_management,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",How many heads of the departments are older th...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ...",(head['age'] > 56).sum(),"{0: {'department': ['Department_ID', 'Name', '...",how many heads of the departments are older th...
1,department_management,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...","List the name, born state and age of the heads...","['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ...","head[['name', 'born_state', 'age']].sort_value...","{0: {'department': ['Department_ID', 'Name', '...","list the name, born state and age of the heads..."
2,department_management,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","List the creation year, name and budget of eac...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ...","department[['creation', 'name', 'budget_in_bil...","{0: {'department': ['Department_ID', 'Name', '...","list the creation year, name and budget of eac..."
3,department_management,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",What are the maximum and minimum budget of the...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ...","department['budget_in_billions'].agg(['max', '...","{0: {'department': ['Department_ID', 'Name', '...",what are the maximum and minimum budget of the...
4,department_management,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",What is the average number of employees of the...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ...",department.loc[lambda x: x['ranking'].between(...,"{0: {'department': ['Department_ID', 'Name', '...",what is the average number of employees of the...
...,...,...,...,...,...,...,...,...,...,...
20317,insurance_fnol,"SELECT t2.date_opened , t2.date_closed FROM c...","['SELECT', 't2.date_opened', ',', 't2.date_clo...","['select', 't2', '.', 'date_opened', ',', 't2'...",Find all the policies associated with the cust...,"['Retrieve', 'the', 'open', 'and', 'close', 'd...","{'from': {'table_units': [['table_unit', 0], [...","customers.merge(customers_policies, on='custom...","{0: {'Customers': ['Customer_ID', 'Customer_na...",find all the policies associated with the cust...
20318,insurance_fnol,"SELECT t2.date_opened , t2.date_closed FROM c...","['SELECT', 't2.date_opened', ',', 't2.date_clo...","['select', 't2', '.', 'date_opened', ',', 't2'...",The open and close dates of all policies used ...,"['What', 'are', 'the', 'open', 'and', 'close',...","{'from': {'table_units': [['table_unit', 0], [...","customers.merge(customers_policies, on='custom...","{0: {'Customers': ['Customer_ID', 'Customer_na...",the open and close dates of all policies used ...
20320,medicine_enzyme_interaction,SELECT count(*) FROM enzyme,"['SELECT', 'count', '(', '*', ')', 'FROM', 'en...","['select', 'count', '(', '*', ')', 'from', 'en...",The total count of enzymes are.,"['What', 'is', 'the', 'total', 'count', 'of', ...","{'from': {'table_units': [['table_unit', 1]], ...",enzyme.shape[0],"{0: {'medicine': ['id', 'name', 'Trade_Name', ...","the total count of enzymes are. | enzyme : id,..."
20321,medicine_enzyme_interaction,SELECT name FROM enzyme ORDER BY name DESC,"['SELECT', 'name', 'FROM', 'enzyme', 'ORDER', ...","['select', 'name', 'from', 'enzyme', 'order', ...",List the names of enzymes in descending lexico...,"['List', 'the', 'name', 'of', 'enzymes', 'in',...","{'from': {'table_units': [['table_unit', 1]], ...","enzyme.sort_values('name', ascending=False)['n...","{0: {'medicine': ['id', 'name', 'Trade_Name', ...",list the names of enzymes in descending lexico...
20322,medicine_enzyme_interaction,SELECT name FROM enzyme ORDER BY name DESC,"['SELECT', 'name', 'FROM', 'enzyme', 'ORDER', ...","['select', 'name', 'from', 'enzyme', 'order', ...","Enzymes are in descending order, what is their...","['What', 'are', 'the', 'names', 'of', 'enzymes...","{'from': {'table_units': [['table_unit', 1]], ...","enzyme.sort_values('name', ascending=False)['n...","{0: {'medicine': ['id', 'name', 'Trade_Name', ...","enzymes are in descending order, what is their..."

In [39]:
i=18040
merged_df.iloc[i]['query'],merged_df.iloc[i]['input'], merged_df.iloc[i]['''sql'''], merged_df.iloc[i]['''tables''']

('SELECT DISTINCT country FROM singer WHERE age  >  20',
 'what is the count of countries whose singers are above the age of 20? | singer : Singer_ID, Name, Country, Song_Name, Song_release_year, Age, Is_male',
 "{'from': {'table_units': [['table_unit', 1]], 'conds': []}, 'select': [True, [[0, [0, [0, 10, False], None]]]], 'where': [[False, 3, [0, [0, 13, False], None], 20.0, None]], 'groupBy': [], 'having': [], 'orderBy': [], 'limit': None, 'intersect': None, 'union': None, 'except': None}",
 "{0: {'stadium': ['Stadium_ID', 'Location', 'Name', 'Capacity', 'Highest', 'Lowest', 'Average']}, 1: {'singer': ['Singer_ID', 'Name', 'Country', 'Song_Name', 'Song_release_year', 'Age', 'Is_male']}, 2: {'concert': ['concert_ID', 'concert_Name', 'Theme', 'Stadium_ID', 'Year']}, 3: {'singer_in_concert': ['concert_ID', 'Singer_ID']}}")

In [20]:
import pandas as pd
merged_df = pd.read_csv('/home/chirayu.tripathi/t5/active_passive/paraphrased_new.csv')

In [32]:
drop_index = []
count = 0
for index,row in merged_df.iterrows():
    if len(row['question'].split(' '))<5:
        drop_index.append(index)
        count+=1
        print(row['question'])
        print('-'*20)

Show all allergy types.
--------------------
Show all majors.
--------------------
Who advises student 1004?
--------------------
List every album's title.
--------------------
List Aerosmith's albums.
--------------------
List all media types.
--------------------
Show all transaction types.
--------------------
Show all team names.
--------------------
Show all product sizes.
--------------------
Show all product colors.
--------------------
Show all donor names.
--------------------
Show all directors.
--------------------
Who directed Avatar?
--------------------
How many reviewers listed?
--------------------
List all restaurant types.
--------------------
Return all detention summaries.
--------------------
Who are Bob's friends?
--------------------
How many students exist?
--------------------
Show all investor details.
--------------------
What are the advisors
--------------------
List all vehicle id
--------------------
How many vehicles exist?
--------------------
what cities in texas
--------------------
what are the states
--------------------
list the states
--------------------
what states neighbor kentucky
--------------------
which states border kentucky
--------------------
what states border kentucky
--------------------
what state borders kentucky
--------------------
what states surround kentucky
--------------------
which state borders kentucky
--------------------
which states adjoin kentucky
--------------------
states bordering kentucky
--------------------
which state border kentucky
--------------------
rivers in illinois
--------------------
where is springfield
--------------------
population of boulder
--------------------
people in boulder
--------------------
whats the largest city
--------------------
what is largest capital
--------------------
where are mountains
--------------------
where is mount whitney
--------------------
where is massachusetts
--------------------
top syntactic parsing author
--------------------
chi papers
--------------------
papers at chi
--------------------
papers in chi
--------------------
chi
--------------------
Papers about chi
--------------------
Papers on chi
--------------------
papers by sharon goldwater
--------------------
sharon goldwater papers
--------------------
Papers by sharon goldwater
--------------------
sharon goldwater 's papers
--------------------
keyphrases by Luke Zettlemoyer
--------------------
top dependent types papers
--------------------
Question Answering research papers
--------------------
papers on Question Answering
--------------------
papers about Question Answering
--------------------
Papers about Question Answering
--------------------
Question Answering experiments
--------------------
Question Answering papers
--------------------
Question Answering publications
--------------------
papers for Question Answering
--------------------
subhasis chaudhuri
--------------------
brian curless convolution paper
--------------------
convolution by brian curless
--------------------
Liwen Xiong publication 2015
--------------------
TAIL papers in NIPS
--------------------
papers on TAIL NIPS
--------------------
acl 2016 authors
--------------------
author published acl 2016
--------------------
semantic parsing dataset
--------------------
datasets for semantic parsing
--------------------
semantic parsing datasets
--------------------
datasets with semantic parsing
--------------------
datasets mentioned at ACL
--------------------
Datasets by jitendra malik
--------------------
recent deep learning papers
--------------------
new deep learning papers
--------------------
latest deep learning papers
--------------------
newest deep learning papers
--------------------
papers citing Daniel Jurafsky
--------------------
citations for Daniel Jurafsky
--------------------
parsing top papers
--------------------
most cited parsing papers
--------------------
highly cited parsing papers
--------------------
papers from 2014
--------------------
2014 papers
--------------------
topics at ACL 2014
--------------------
Papers on WebKB
--------------------
papers about WebKB
--------------------
papers using WebKB
--------------------
papers that use WebKB
--------------------
WebKB papers
--------------------
papers that used WebKB
--------------------
conferences in 2013
--------------------
papers in pldi 2015
--------------------
pldi papers in 2015
--------------------
papers from pldi 2015
--------------------
pldi papers 2015
--------------------
pldi 2015 conference
--------------------
List today 's journals
--------------------
2014 papers using ImageNet
--------------------
question answering 2016 papers
--------------------
NIPS authors
--------------------
conferences that mention ImageNet
--------------------
first deep learning paper
--------------------
venue for Trophic Cascade
--------------------
conferences for Trophic Cascade
--------------------
ACL papers by author
--------------------
authors working on ImageNet
--------------------
How many countries exist?
--------------------
Describe the section h.
--------------------
What is Kyle's id?
--------------------
Fetch names of advisors.
--------------------
Display all the majors.
--------------------
Identify the different majors.
--------------------
V2
--------------------
Who joined latest?
--------------------
Return all item details.
--------------------
Number of players
--------------------
How many parties exist?
--------------------
Describe all restaurants.
--------------------
Whose email is "emmarohan0@gmail.com"?
--------------------
How many courses exist?
--------------------
How many clubs exist?
--------------------
Find Alice's second-"level-of-friends".
--------------------
Which artworks are there?
--------------------
How may schools exist?
--------------------
Which are the labels?
--------------------
How many customers exist?
--------------------
Which lessons were canceled?
--------------------
Keyword: Faculty
--------------------
How many airlines exist?
--------------------
which cities in texas?
--------------------
display the state names
--------------------
Where is Tennessee located?
--------------------
which new jersey
--------------------
Which states border Kentucky?
--------------------
how many people live
--------------------
Which state borders Kentucky?
--------------------
What states border Texas?
--------------------
Where are mountains located?
--------------------
Where is Mount Whitney?
--------------------
most syntactic parsing papers
--------------------
1
--------------------
Papers authored by Chi
--------------------
papers from chi
--------------------
Papers about China
--------------------
Papers concerned with China.
--------------------
What did Sharon write?
--------------------
keyphrases by Luke Zettlemoyer.
--------------------
How many papers exist?
--------------------
Answer the following questions.
--------------------
papers on question answering
--------------------
Question answering experiments
--------------------
The results are printed.
--------------------
Question Answering publications.
--------------------
chaudhuri
--------------------
convolution by Brian Curless
--------------------
Datasets for semantic parsing
--------------------
Semantic parsing datasets
--------------------
Semantic parsing dataset
--------------------
Datasets of jitendra malik
--------------------
Latest deep learning papers
--------------------
who cites oren etzioni
--------------------
papers for parsing
--------------------
papers authored by 2014
--------------------
Papers in WebKB
--------------------
papers and WebKB
--------------------
articles using WebKB
--------------------
Papers from PLDI 2015?
--------------------
http://pldi2015.cs.umass.edu/paper/list
--------------------
2015 PLDI Conference
--------------------
How many singers exist?
--------------------
return (numMatches);
--------------------
Describe the "h" section.
--------------------
How many are there?
--------------------
Courses are:
--------------------
Her name is ______.
--------------------
Different food allergies are.
--------------------
What is Cat's allergy?
--------------------
Show male student ids.
--------------------
All male students are.
--------------------
City | Students
--------------------
Nancy Edwards's address is.
--------------------
List of all playlists.
--------------------
The editors ages are:
--------------------
Some editors are.
--------------------
How many races are?
--------------------
All music genres are:
--------------------
All phone numbers.
--------------------

In [30]:
# drop_index

In [31]:
count

193

In [24]:
merged_df.drop(labels = drop_index,axis=0,inplace=True)

In [25]:
merged_df.to_csv('/home/chirayu.tripathi/t5/active_passive/paraphrased_new.csv',index=False)

In [26]:
merged_df

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql,pandas,tables,input
0,department_management,SELECT count(*) FROM head WHERE age > 56,"['SELECT', 'count', '(', '*', ')', 'FROM', 'he...","['select', 'count', '(', '*', ')', 'from', 'he...",How many heads of the departments are older th...,"['How', 'many', 'heads', 'of', 'the', 'departm...","{'from': {'table_units': [['table_unit', 1]], ...",(head['age'] > 56).sum(),"{0: {'department': ['Department_ID', 'Name', '...",how many heads of the departments are older th...
1,department_management,"SELECT name , born_state , age FROM head ORD...","['SELECT', 'name', ',', 'born_state', ',', 'ag...","['select', 'name', ',', 'born_state', ',', 'ag...","List the name, born state and age of the heads...","['List', 'the', 'name', ',', 'born', 'state', ...","{'from': {'table_units': [['table_unit', 1]], ...","head[['name', 'born_state', 'age']].sort_value...","{0: {'department': ['Department_ID', 'Name', '...","list the name, born state and age of the heads..."
2,department_management,"SELECT creation , name , budget_in_billions ...","['SELECT', 'creation', ',', 'name', ',', 'budg...","['select', 'creation', ',', 'name', ',', 'budg...","List the creation year, name and budget of eac...","['List', 'the', 'creation', 'year', ',', 'name...","{'from': {'table_units': [['table_unit', 0]], ...","department[['creation', 'name', 'budget_in_bil...","{0: {'department': ['Department_ID', 'Name', '...","list the creation year, name and budget of eac..."
3,department_management,"SELECT max(budget_in_billions) , min(budget_i...","['SELECT', 'max', '(', 'budget_in_billions', '...","['select', 'max', '(', 'budget_in_billions', '...",What are the maximum and minimum budget of the...,"['What', 'are', 'the', 'maximum', 'and', 'mini...","{'from': {'table_units': [['table_unit', 0]], ...","department['budget_in_billions'].agg(['max', '...","{0: {'department': ['Department_ID', 'Name', '...",what are the maximum and minimum budget of the...
4,department_management,SELECT avg(num_employees) FROM department WHER...,"['SELECT', 'avg', '(', 'num_employees', ')', '...","['select', 'avg', '(', 'num_employees', ')', '...",What is the average number of employees of the...,"['What', 'is', 'the', 'average', 'number', 'of...","{'from': {'table_units': [['table_unit', 0]], ...",department.loc[lambda x: x['ranking'].between(...,"{0: {'department': ['Department_ID', 'Name', '...",what is the average number of employees of the...
...,...,...,...,...,...,...,...,...,...,...
19618,insurance_fnol,"SELECT t2.date_opened , t2.date_closed FROM c...","['SELECT', 't2.date_opened', ',', 't2.date_clo...","['select', 't2', '.', 'date_opened', ',', 't2'...",Find all the policies associated with the cust...,"['Retrieve', 'the', 'open', 'and', 'close', 'd...","{'from': {'table_units': [['table_unit', 0], [...","customers.merge(customers_policies, on='custom...","{0: {'Customers': ['Customer_ID', 'Customer_na...",find all the policies associated with the cust...
19619,insurance_fnol,"SELECT t2.date_opened , t2.date_closed FROM c...","['SELECT', 't2.date_opened', ',', 't2.date_clo...","['select', 't2', '.', 'date_opened', ',', 't2'...",The open and close dates of all policies used ...,"['What', 'are', 'the', 'open', 'and', 'close',...","{'from': {'table_units': [['table_unit', 0], [...","customers.merge(customers_policies, on='custom...","{0: {'Customers': ['Customer_ID', 'Customer_na...",the open and close dates of all policies used ...
19620,medicine_enzyme_interaction,SELECT count(*) FROM enzyme,"['SELECT', 'count', '(', '*', ')', 'FROM', 'en...","['select', 'count', '(', '*', ')', 'from', 'en...",The total count of enzymes are.,"['What', 'is', 'the', 'total', 'count', 'of', ...","{'from': {'table_units': [['table_unit', 1]], ...",enzyme.shape[0],"{0: {'medicine': ['id', 'name', 'Trade_Name', ...","the total count of enzymes are. | enzyme : id,..."
19621,medicine_enzyme_interaction,SELECT name FROM enzyme ORDER BY name DESC,"['SELECT', 'name', 'FROM', 'enzyme', 'ORDER', ...","['select', 'name', 'from', 'enzyme', 'order', ...",List the names of enzymes in descending lexico...,"['List', 'the', 'name', 'of', 'enzymes', 'in',...","{'from': {'table_units': [['table_unit', 1]], ...","enzyme.sort_values('name', ascending=False)['n...","{0: {'medicine': ['id', 'name', 'Trade_Name', ...",list the names of enzymes in descending lexico...
19622,medicine_enzyme_interaction,SELECT name FROM enzyme ORDER BY name DESC,"['SELECT', 'name', 'FROM', 'enzyme', 'ORDER', ...","['select', 'name', 'from', 'enzyme', 'order', ...","Enzymes are in descending order, what is their...","['What', 'are', 'the', 'names', 'of', 'enzymes...","{'from': {'table_units': [['table_unit', 1]], ...","enzyme.sort_values('name', ascending=False)['n...","{0: {'medicine': ['id', 'name', 'Trade_Name', ...","enzymes are in descending order, what is their..."

In [28]:
merged_df.iloc[0]['input']

'how many heads of the departments are older than 56 ? | head : head_ID, name, born_state, age'

In [33]:
df = pd.read_csv('/home/chirayu.tripathi/t5/active_passive/train.csv')

In [34]:
df['source_text'] =

,source_text,target_text
0,code: how big is new mexico | state : state_na...,"state[state['state_name'] == ""new mexico""]['ar..."
1,code: what is the area of new mexico | state :...,"state[state['state_name'] == ""new mexico""]['ar..."
2,code: how large is new mexico | state : state_...,"state[state['state_name'] == ""new mexico""]['ar..."
3,code: what is the area of the new mexico state...,"state[state['state_name'] == ""new mexico""]['ar..."
4,code: what is the size of new mexico | state :...,"state[state['state_name'] == ""new mexico""]['ar..."
...,...,...
4467,code: what is the name of the singer with the ...,"singer[['name', 'net_worth_millions']].sort_va..."
4468,code: what is the name of the singer who is wo...,"singer[['name', 'net_worth_millions']].sort_va..."
4469,code: please show the most common citizenship ...,singer.groupby('citizenship').agg(col2 = ('cit...
4470,code: what is the most common singer citizensh...,singer.groupby('citizenship').agg(col2 = ('cit...
4471,code: how many available features are there in...,pd.series(other_available_features.shape[0])

In [2]:
import pandas as pd
df = pd.read_csv('/home/chirayu.tripathi/t5/active_passive/paraphrased_new.csv')

In [8]:
df[df['question'].str.contains('What is the venue of the competition')]

,db_id,query,query_toks,query_toks_no_value,question,question_toks,sql,pandas,tables,input
6231,city_record,SELECT T3.venue FROM city AS T1 JOIN hosting_c...,"['SELECT', 'T3.venue', 'FROM', 'city', 'AS', '...","['select', 't3', '.', 'venue', 'from', 'city',...","What is the venue of the competition ""1994 FIF...","['What', 'is', 'the', 'venue', 'of', 'the', 'c...","{'from': {'table_units': [['table_unit', 0], [...","(pd.merge(pd.merge(city, hosting_city, on='cit...","{0: {'city': ['City_ID', 'City', 'Hanzi', 'Han...","what is the venue of the competition ""1994 fif..."

In [14]:
i = 6231
print('Question - ',df.iloc[i]['question'])
print('Input - ','pandas: '+df.iloc[i]['input'])

Question -  What is the venue of the competition "1994 FIFA World Cup qualification" hosted by "Nanjing ( Jiangsu )"?
Input -  pandas: what is the venue of the competition "1994 fifa world cup qualification" hosted by "nanjing ( jiangsu )"? | city : City_ID, City, Hanzi, Hanyu_Pinyin, Regional_Population, GDP | hosting_city : Year, Match_ID, Host_City | match : Match_ID, Date, Venue, Score, Result, Competition